# Generated by pub
# See https://www.dartlang.org/tools/pub/glossary#lockfile
packages:
  animated_text_kit:
    dependency: "direct main"
    description:
      name: animated_text_kit
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  boolean_selector:

